#pragma once
#ifndef COMMANDSNAME_H
#define COMMANDSNAME_H

#define PRINT_CMD "PRINTCOMMAND"
#define CREATE_CUSTOM_CMD "CREATECUSTOMCMD"
#define RETRIEVE_CUSTOM_CMD "RETRIEVECUSTOMCMD"
#define CUSTOM_LIST_CMD "CUSTOMLISTCMD"

#endif // COMMANDSNAME_H